### ISSUE TITLE
Odoo integration - possible to get test login?

### ISSUE THREAD

**Issue by k-holland** [EE/moodle_auth_odoo#4]
It looks like this plugin requires a third-party signup based service. Might you be able to setup a demonstration URL and login with relevant user test data please so that I can see and test the plugin in action? There is a wide range of Odoo apps on their website at https://www.odoo.com/trial and it's not immediately clear to someone new to the service, which app in particular is being integrated with.

**Comment by ludwiktrammer** [comment]
What do you mean by "a third-party signup based service"? The plugin uses Odoo core's APIs. It will work no matter which Odoo modules are present (so any choise from https://www.odoo.com/trial would be ok).

**Comment by k-holland** [comment]
Hi Ludwig

I created a test online account with Odoo, setting up additional test users, and used the admin email, password and URL in the moodle auth/odoo settings page. I also created a new test user on my test moodle site, with the same test username with auth method of Odoo.

When I try to login using this test account I am getting the following error:
Notice: xmlrpc: Traceback (most recent call last): File "/home/odoo/src/odoo/saas-10/openerp/service/wsgi_server.py", line 56, in xmlrpc_return result = openerp.http.dispatch_rpc(service, method, params) File "/home/odoo/src/odoo/saas-10/openerp/http.py", line 114, in dispatch_rpc result = dispatch(method, params) File "/home/odoo/src/odoo/saas-10/openerp/service/common.py", line 57, in dispatch return g[exp_method_name](*params) File "/home/odoo/src/odoo/saas-10/openerp/service/common.py", line 29, in exp_authenticate res_users = openerp.registry(db)['res.users'] File "/home/odoo/src/odoo/saas-10/openerp/**init**.py", line 50, in registry return modules.registry.RegistryManager.get(database_name) File "/home/odoo/src/odoo/saas-10/openerp/modules/registry.py", line 360, in get update_module) File "/home/odoo/src/odoo/saas-10/openerp/modules/registry.py", line 377, in new registry = Registry(db_name) File "/home/odoo/src/odoo/saas-10/openerp/modules/registry.py", line 64, in in /srv/www/--/public_html/--/auth/odoo/xmlrpc.php on line 12

**Comment by ludwiktrammer** [comment]
Ok, thank you for the report. I will look into this (hopefully tomorrow).
